Added Readme for Laravel training
LSAC-ONG/training pull request #24
Opened 2020-09-19 17:19 UTC by Andrei250

2020-09-20 11:23 UTC, Pirvu2k requested changes

2020-09-20 11:23 UTC, Pirvu2k commented on Laravel/README.md
> +Laravel este unul dintre cele mai folosite framework-uri web de PHP si este de tip MVP (Model - View - Controller). Acesta a evoluat foarte mult in ultimii ani, ajungand in prezent la versiunea 8.
tip MVC, nu MVP

2020-09-20 11:23 UTC, Pirvu2k commented on Laravel/README.md
> +- Models and Eloquent
As pune models fix dupa database si inainte de forms

2020-09-20 14:28 UTC, BLSAlin commented
Personal, as mai adauga niste informatii in README punctuale despre ceea ce o sa faceti. 

De exemplu: ai putea lasa la routing o explicatie pentru concept si poate 2-3 chestii mai specifice. Stiu ca in final ramane un video cu ceea ce se va face, dar zic ca ar ajuta sa fie ceva in format readable. (Eu, cel putin, prefer variantele text)

Este doar o sugestie totusi.

2020-09-21 16:57 UTC, Pirvu2k approved these changes

2020-09-21 16:57 UTC, merged